export const fakeData = [
  {
    position: "Assistant Manager",
    details: {
      responsibility: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      requirements: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      other: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      contact: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
    },
  },
  {
    position: "Blockchain Engineer",
    details: {
      responsibility: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      requirements: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      other: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      contact: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
    },
  },
  {
    position: "Software Engineer",
    details: {
      responsibility: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      requirements: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      other: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      contact: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
    },
  },
  {
    position: "Marketing",
    details: {
      responsibility: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      requirements: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      other: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
      contact: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu ipsum nisl. Fusce ut interdum leo. Morbi feugiat mauris id risus posuere, tincidunt aliquet tortor tristique. Curabitur nec hendrerit leo. Sed maximus pharetra ipsum non aliquam. Nullam tincidunt elementum laoreet. Aenean consequat pharetra tempor. Sed non posuere nunc. Sed at pharetra nisl, et consequat sapien. Fusce volutpat, est ut maximus condimentum, elit ante efficitur turpis, eu pulvinar velit magna ut purus. Aenean eu finibus enim. Nullam a diam ut leo molestie luctus. Proin nibh velit, consectetur sed enim et, tincidunt tincidunt lorem. Phasellus ornare accumsan dui, vitae ornare magna placerat vitae. Sed pharetra pharetra euismod.</p>",
    },
  },
];
