name: Continuous Deployment
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, linux, X64]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - run: echo $(pwd)
      # - name: Install dependencies
      #   run: yarn
      # - name: Build
      #   run: yarn build
      # - name: Deploy
      #   uses: jakejarvis/s3-sync-action@v0.5.0
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.STAGING_AWS_S3_BUCKET }}
      #   env:
      #   CI: true
