name: Test
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
    - name: Install modules
      with:
        cmd: install
    - name: Run lint check
      with:
        cmd: run lint
  Build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
    - name: Install modules
      with:
        cmd: install
    - name: Run build check
      with:
        cmd: build
