name: Test
on: push
jobs:
  Lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run lint # will run `yarn build` command
  Build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: Run build check
        run: npm run build

          # Build-test:
          #   runs-on: ubuntu-latest
          #   steps:
          #   - uses: actions/checkout@v2
          #   - name: Install modules
          #     run: npm install
          #   - name: Run build check
          #     run: npm run build
  # Lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: borales/actions-yarn@v2.0.0
  #   - name: Install modules
  #     run: yarn install
  #   - name: Run lint check
  #     run: yarn run lint
  # Build-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: borales/actions-yarn@v2.0.0
  #   - name: Install modules
  #     run: yarn install
  #   - name: Run build check
  #     run: yarn run build
